-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 18:58:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema impuesto_predial
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `impuesto_predial` ;

-- -----------------------------------------------------
-- Schema impuesto_predial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `impuesto_predial` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `impuesto_predial` ;

-- -----------------------------------------------------
-- Table `impuesto_predial`.`contribuyentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuesto_predial`.`contribuyentes` (
  `id_contribuyente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `cedula` VARCHAR(10) NOT NULL,
  `correo_electronico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_contribuyente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `impuesto_predial`.`impuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuesto_predial`.`impuestos` (
  `id_impuesto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `valor_mensual` DECIMAL(10,2) NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  PRIMARY KEY (`id_impuesto`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `impuesto_predial`.`propiedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuesto_predial`.`propiedades` (
  `id_propiedad` INT NOT NULL AUTO_INCREMENT,
  `id_contribuyente` INT NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `valor_catastral` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_propiedad`),
  CONSTRAINT `propiedades_ibfk_1`
    FOREIGN KEY (`id_contribuyente`)
    REFERENCES `impuesto_predial`.`contribuyentes` (`id_contribuyente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_contribuyente` ON `impuesto_predial`.`propiedades` (`id_contribuyente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `impuesto_predial`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `impuesto_predial`.`pagos` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `id_impuesto` INT NOT NULL,
  `id_propiedad` INT NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `valor_pagado` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pago`),
  CONSTRAINT `pagos_ibfk_1`
    FOREIGN KEY (`id_impuesto`)
    REFERENCES `impuesto_predial`.`impuestos` (`id_impuesto`),
  CONSTRAINT `pagos_ibfk_2`
    FOREIGN KEY (`id_propiedad`)
    REFERENCES `impuesto_predial`.`propiedades` (`id_propiedad`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_impuesto` ON `impuesto_predial`.`pagos` (`id_impuesto` ASC) VISIBLE;

CREATE INDEX `id_propiedad` ON `impuesto_predial`.`pagos` (`id_propiedad` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
